language: julia
os:
    - linux
julia:
    - 0.3
    - release
    - nightly
notifications:
    email: false
before_install:
    - sudo apt-get update -qq -y
    - sudo apt-get install libcfitsio3 -y
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("FITSIO"); Pkg.test("FITSIO"; coverage=true)';
after_success:
    - julia -e 'cd(Pkg.dir("FITSIO")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
