site_name:        FITSIO.jl
repo_url:         https://github.com/JuliaAstro/FITSIO.jl
site_description: Flexible Image Transport System (FITS) support for Julia
site_author:      FITSIO.jl developers

theme: cinder

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
